// Generated by CoffeeScript 1.9.3
var _, deckCD, ref, render, url;

ref = location.href.match(/DECK_CD=(\d+)/), _ = ref[0], deckCD = ref[1];

url = "http://teamys.net/deckbuilder/build_add.php?DECK_CD=" + deckCD + "&select_DECK_CD=" + deckCD;

render = function(target, cards) {
  var $body, $content, $image, $page, card, html, i, j, len, results;
  html = "<html>\n  <head>\n    <style>\n      * {\n        margin:  0px;\n        padding: 0px;\n      }\n      #content {\n        position: absolute;\n        top:  0px;\n        left: 0px;\n        width: 1050px;\n      }\n      #page-template {\n        display: none;\n      }\n      .page img.template {\n        width: 100%;\n        z-index: -1;\n        position: absolute;\n        top:  0px;\n        left: 0px;\n      }\n      .page img.card {\n        width:  222px;\n        height: 311px;\n      }\n      .page {\n        position: relative;\n        height: 743px;\n        padding-left: 81px;\n        padding-top:  60px;\n        box-sizing: border-box;\n        -webkit-box-sizing: border-box;\n        -moz-box-sizing: border-box;\n        -o-box-sizing: border-box;\n        -ms-box-sizing: border-box;\n        page-break-after: always;\n      }\n    </style>\n  </head>\n  <body>\n    <div class=\"page\" id=\"page-template\">\n      <img class=\"template\" src=\"http://joshin.co:3000/template.png\"></img>\n    </div>\n    <div id=\"content\"></div>\n  </body>\n</html>";
  target.document.write(html);
  $body = $(target.document.body);
  $content = $body.find('#content');
  $page = void 0;
  results = [];
  for (j = 0, len = cards.length; j < len; j++) {
    card = cards[j];
    results.push((function() {
      var k, ref1, results1;
      results1 = [];
      for (i = k = 1, ref1 = card.number; 1 <= ref1 ? k <= ref1 : k >= ref1; i = 1 <= ref1 ? ++k : --k) {
        $image = $('<img>').attr('src', card.url).addClass('card');
        if (!$page || $page.find('img.card').length >= 8) {
          $page = $body.find('#page-template').clone().removeAttr('id');
          $content.append($page);
        }
        results1.push($page.append($image));
      }
      return results1;
    })());
  }
  return results;
};

$.get(url, {}, function(data) {
  var $rows, cards, numberOfRows;
  $rows = $(data).find('#addForm #addForm').find('.line1,.line2');
  cards = [];
  numberOfRows = $rows.length;
  return $rows.each(function(index, row) {
    var $link, $row, id, name, number, searchUrl;
    $row = $(row);
    $link = $row.find('#name a');
    name = $link.text();
    number = $row.find('select').val();
    url = $link.attr('href');
    id = url.replace(/^.+&id=(\d+)$/, '$1');
    searchUrl = "/cardSeach/cardSeach_controller.php?f=card_view&id=" + id;
    return $.get(searchUrl, {}, function(data) {
      var $image, bigger_url, exp, ref1;
      $image = $(data).find('#deck_sea .line1 img');
      url = $image.attr('src');
      if (!url) {
        numberOfRows--;
        alert("「" + name + "」の情報の取得に失敗しました。\n(TeamY's のせいだよ！)");
        return;
      }
      ref1 = url.match(/card\/([^\/]+)\/x?(\d+)/), _ = ref1[0], exp = ref1[1], id = ref1[2];
      if (!(id && url)) {
        return;
      }
      bigger_url = "http://teamys.net/include/mtg/img/card-big/" + exp + "/" + id + ".jpg";
      cards.push({
        url: bigger_url,
        number: number
      });
      if (cards.length === numberOfRows) {
        return render(window.open(), cards);
      }
    });
  });
});
